version: "3.8"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: prod_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PROD_DB_HOST=db
      - PROD_DB_USER=root
      - PROD_DB_PASSWORD=123456
      - PROD_DB_NAME=prod_db
    depends_on:
      - db
    command: >
      sh -c "
      npx sequelize-cli db:migrate &&
      npx sequelize-cli db:seed:all &&
      node dist/server.js"
