version: "3.8"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: prod_db
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PROD_DB_HOST=0.0.0.0
      - PROD_DB_USER=root
      - PROD_DB_PASSWORD=123456
      - PROD_DB_NAME=prod_db
    depends_on:
      - db
